labjack:
  ip_address: "192.168.1.3"
  channels: ["AIN0", "AIN1", "AIN2"]
  sample_interval: 0.1  # 초 단위
  voltage_ranges: [10.0, 10.0, 10.0]

logging:
  log_file: "logs/run.log"

data:
  save_dir: "data"
  file_prefix: "measurement_"
